name: Matej Pribis - neuroscience and psychiatry
highlighter: rouge

email: matejpribis@gmail.com
description: >-
  The site about the joined worlds of neuroscience and psychiatry.
baseurl: "/"
url: "pribism.github.io"


